//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThongKeSanPham
    {
        public string maChiTietThongKeSanPham { get; set; }
        public string maThongKeSanPham { get; set; }
        public string maSanPham { get; set; }
        public Nullable<int> soLuongBan { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<double> thanhTien { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual ThongKeSanPham ThongKeSanPham { get; set; }

        public override string ToString()
        {
            return maChiTietThongKeSanPham;
        }
    }
}
