//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThongKeNguyenLieu
    {
        public string maChiTietThongKeNguyenLieu { get; set; }
        public string maThongKeNguyenLieu { get; set; }
        public string maNguyenLieu { get; set; }
        public Nullable<int> soLuongBan { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<double> thanhTien { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual ThongKeNguyenLieu ThongKeNguyenLieu { get; set; }

        public override string ToString()
        {
            return maChiTietThongKeNguyenLieu;
        }
    }
}
