//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThongKe
    {
        public string maChiTietThongKe { get; set; }
        public string maThongKe { get; set; }
        public string maNhanVien { get; set; }
        public Nullable<int> soLuongHoaDon { get; set; }
        public Nullable<int> soLuongBan { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<double> thanhTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThongKe ThongKe { get; set; }
    }
}
