//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietChamCong
    {
        public string maChamCong { get; set; }
        public string maNhanVien { get; set; }
        public System.DateTime ngayLam { get; set; }
        public string thu { get; set; }
        public System.TimeSpan gioVao { get; set; }
        public System.DateTime gioRa { get; set; }
        public System.DateTime vaoTre { get; set; }
        public System.DateTime raSom { get; set; }
        public System.DateTime soGioLam { get; set; }
        public Nullable<int> trangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public override string ToString()
        {
            return maChamCong;
        }
    }
}
