//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietXuatNhapNguyenLieu
    {
        public string maPhieuXuat { get; set; }
        public string maNguyenLieu { get; set; }
        public double thanhTien { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual PhieuXuatNguyenLieu PhieuXuatNguyenLieu { get; set; }
    }
}
