//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietNguyenLieu()
        {
            this.ChiTietPhieuNhapNguyenLieux = new HashSet<ChiTietPhieuNhapNguyenLieu>();
            this.ChiTietPhieuXuatNguyenLieux = new HashSet<ChiTietPhieuXuatNguyenLieu>();
        }
    
        public string maNguyenLieu { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<System.DateTime> ngayHetHan { get; set; }
        public Nullable<double> donGia { get; set; }
        public string donViTinh { get; set; }
        public Nullable<System.DateTime> ngayNhap { get; set; }
        public Nullable<System.DateTime> ngayXuat { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapNguyenLieu> ChiTietPhieuNhapNguyenLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuXuatNguyenLieu> ChiTietPhieuXuatNguyenLieux { get; set; }
    }
}
