//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetCa
    {
        public string maKetCa { get; set; }
        public string maNhanVien { get; set; }
        public Nullable<System.DateTime> gioBatDau { get; set; }
        public Nullable<System.DateTime> gioKetThuc { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> tongTienBan { get; set; }
        public Nullable<double> tienDauCa { get; set; }
        public Nullable<double> tongDoanhThu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public override string ToString()
        {
            return maKetCa;
        }
    }
}
