//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luong
    {
        public string maLuong { get; set; }
        public string maNhanVien { get; set; }
        public System.DateTime tuNgay { get; set; }
        public System.DateTime denNgay { get; set; }
        public System.DateTime tongGioLam { get; set; }
        public double thanhTien { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
