//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenLieu()
        {
            this.ChiTietPhieuNhapNguyenLieux = new HashSet<ChiTietPhieuNhapNguyenLieu>();
            this.ChiTietXuatNhapNguyenLieux = new HashSet<ChiTietXuatNhapNguyenLieu>();
        }
    
        public string maNguyenLieu { get; set; }
        public string tenNguyenLieu { get; set; }
        public double donGia { get; set; }
        public int soLuong { get; set; }
        public string donViTinh { get; set; }
        public System.DateTime ngayHetHan { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public string maLoaiNguyenLieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapNguyenLieu> ChiTietPhieuNhapNguyenLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXuatNhapNguyenLieu> ChiTietXuatNhapNguyenLieux { get; set; }
        public virtual LoaiNguyenLieu LoaiNguyenLieu { get; set; }
    }
}
