//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenLieu()
        {
            this.ChiTietPhieuNhapNguyenLieux = new HashSet<ChiTietPhieuNhapNguyenLieu>();
            this.ChiTietXuatNhapNguyenLieux = new HashSet<ChiTietXuatNhapNguyenLieu>();
        }

        public NguyenLieu(
            string maNguyenLieu,
            string tenNguyenLieu,
            double donGia,
            int soLuong,
            string donViTinh,
            DateTime ngayHetHan,
            DateTime ngayNhap,
            string maLoaiNguyenLieu
            )
        {
            this.maNguyenLieu = maNguyenLieu;
            this.tenNguyenLieu = tenNguyenLieu;
            this.donGia = donGia;
            this.soLuong = soLuong;
            this.donViTinh = donViTinh;
            this.ngayHetHan = ngayHetHan;
            this.ngayNhap = ngayNhap;
            this.maLoaiNguyenLieu = maLoaiNguyenLieu;
        }

        public void copyData(NguyenLieu nguyenLieu)
        {
            this.maNguyenLieu = nguyenLieu.maNguyenLieu;
            this.tenNguyenLieu = nguyenLieu.tenNguyenLieu;
            this.donGia = nguyenLieu.donGia;
            this.soLuong = nguyenLieu.soLuong;
            this.donViTinh = nguyenLieu.donViTinh;
            this.ngayHetHan = nguyenLieu.ngayHetHan;
            this.ngayNhap = nguyenLieu.ngayNhap;
            this.maLoaiNguyenLieu = nguyenLieu.maLoaiNguyenLieu;
        }

        public string maNguyenLieu { get; set; }
        public string tenNguyenLieu { get; set; }
        public double donGia { get; set; }
        public int soLuong { get; set; }
        public string donViTinh { get; set; }
        public System.DateTime ngayHetHan { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public string maLoaiNguyenLieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapNguyenLieu> ChiTietPhieuNhapNguyenLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietXuatNhapNguyenLieu> ChiTietXuatNhapNguyenLieux { get; set; }
        public virtual LoaiNguyenLieu LoaiNguyenLieu { get; set; }
    }
}
