//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        public string maNguyenLieu { get; set; }
        public string tenNguyenLieu { get; set; }
        public string maLoaiNguyenLieu { get; set; }
        public Nullable<int> trangThai { get; set; }
    
        public virtual ChiTietNguyenLieu ChiTietNguyenLieu { get; set; }
        public virtual LoaiNguyenLieu LoaiNguyenLieu { get; set; }
    }
}
