//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapNguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhapNguyenLieu()
        {
            this.ChiTietPhieuNhapNguyenLieus = new HashSet<ChiTietPhieuNhapNguyenLieu>();
        }
    
        public string maPhieuNhap { get; set; }
        public System.DateTime ngayNhap { get; set; }
        public double tongThanhTien { get; set; }
        public string maNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuNhapNguyenLieu> ChiTietPhieuNhapNguyenLieus { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
