//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongKeSanPham()
        {
            this.ChiTietThongKeSanPhams = new HashSet<ChiTietThongKeSanPham>();
        }
    
        public string maThongKeSanPham { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<double> tongThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongKeSanPham> ChiTietThongKeSanPhams { get; set; }

        public override string ToString()
        {
            return maThongKeSanPham;
        }
    }
}
