//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanCoffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeNguyenLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongKeNguyenLieu()
        {
            this.ChiTietThongKeNguyenLieux = new HashSet<ChiTietThongKeNguyenLieu>();
        }
    
        public string maThongKeNguyenLieu { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public Nullable<double> tongThanhTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietThongKeNguyenLieu> ChiTietThongKeNguyenLieux { get; set; }

        public override string ToString()
        {
            return maThongKeNguyenLieu;
        }
    }
}
